version: "3.3"

services:

  # Nginx
  nginx:
    build:
      context: ${NGINX_CONFIG_DIR}
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - ${NGINX_LINK_DIR}:${WORKING_DIR}
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${NGINX_CONFIG_DIR}/cert:/etc/nginx/cert
      # - ${NGINX_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONFIG_DIR}/magento.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mariadb
      - php
    working_dir: ${WORKING_DIR}
    hostname: localhost

  # MariaDB
  mariadb:
    build:
      context: ${MARIADB_CONFIG_DIR}
      dockerfile: Dockerfile
      args:
        - TIME_ZONA=${TIME_ZONA}
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_main
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LINK_DIR}:/dump
      - ${MARIADB_LOG_DIR}:/var/log/mysql
      - ${MARIADB_CONFIG_DIR}/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
    working_dir: /dump
    hostname: localhost

  # PHP
  php:
    build:
      context: ${PHP_CONFIG_DIR}
      dockerfile: php-7.4-fpm
      args:
        - WEB_NAME=${WEB_USER_NAME}
        - WEB_ID=${WEB_USER_ID}
        - TIME_ZONA=${TIME_ZONA}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    environment:
      - PHP_IDE_CONFIG=serverName=${HOST_NAME}
    expose:
      - 9000
    volumes:
      - ${PHP_LINK_DIR}:${WORKING_DIR}
      - ${PHP_CONFIG_DIR}/php.ini:/usr/local/etc/php/php.ini
      - ${PHP_CONFIG_DIR}/auth.json:/root/.composer/auth.json
    working_dir: ${WORKING_DIR}
    hostname: ${HOST_NAME}

  # SMTP Server
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    expose:
      - 1025
    ports:
      - 1025:1025
      - 8025:8025
    hostname: localhost

  # ElasticSearch
  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ${ELASTICSEARCH_LINK_DIR}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_LOG_DIR}:/usr/share/elasticsearch/logs
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
